name: Osetek Tennis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23878
title: 'Tw√≥j tenis - Moja pasja!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#f0e936'
    - '#7f7f7f'
    - '#c2c2c2'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
